/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by Keycloakify

export type ThemeName = 'keycloakify-angular-workspace';

export const themeNames: ThemeName[] = ['keycloakify-angular-workspace'];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import('./login/KcContext').KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

/* prettier-ignore-end */
